### PR TITLE
fix(sidebar): highlight active route

### LINKED ISSUE #547: UI/UX: Sidebar is not preserving its state
https://github.com/user-attachments/assets/5929e0a9-faf9-46d9-b48e-044b33eb8f5a

### PR DESCRIPTION
**Pull request by imgullu786**
Closes #547 

## Summary by CodeRabbit

* **New Features**
  * Sidebar navigation now highlights the active section based on the current route.
  * New navigation items added for Spaces and Change Requests.

* **Refactor**
  * Sidebar collapsed state now syncs via two-way binding for more reliable state management.
  * Sidebar sections are driven dynamically and reflect route-aware active status.

### CODE REVIEW

File: frontend/src/components/Sidebar.vue [hunk 1]
```diff
@@ -36,6 +39,9 @@ const themeIcon = computed(() => {
 
 const isSidebarCollapsed  = useStorage("is-sidebar-collapsed", false);
 
+const isSpacesActive = computed(() => route.path.startsWith("/spaces"));
+const isChangeRequestsActive = computed(() => route.path.startsWith("/change-requests"));
+
```
Comment (NagariaHussain) [inline frontend/src/components/Sidebar.vue]: What if we add a third page? 😅

Lot of repetition, we should DRY it up.

**Review by NagariaHussain — CHANGES_REQUESTED** [review]

**Review by NagariaHussain — APPROVED** [review]
